// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createURL = `-- name: CreateURL :exec
INSERT INTO url (original, shorten)
VALUES (?, ?)
`

type CreateURLParams struct {
	Original string
	Shorten  string
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) error {
	_, err := q.db.ExecContext(ctx, createURL, arg.Original, arg.Shorten)
	return err
}

const getOriginalURL = `-- name: GetOriginalURL :one
SELECT 
    original
FROM url
WHERE shorten = ? LIMIT 1
`

func (q *Queries) GetOriginalURL(ctx context.Context, shorten string) (string, error) {
	row := q.db.QueryRowContext(ctx, getOriginalURL, shorten)
	var original string
	err := row.Scan(&original)
	return original, err
}
